import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <div className="flex flex-col h-screen overflow-hidden">
                    {/* Top Navbar */}
                    <header className="shrink-0">
                        <Navbar />
                    </header>

                    {/* Main area */}
                    <div className="flex flex-1 overflow-hidden">
                        {/* Sidebar (no scroll) */}
                        <aside className="w-64 shrink-0">
                            <Sidebar />
                        </aside>

                        {/* Page content (scrollable) */}
                        <main className="flex-1 overflow-y-auto p-4">
                            {children}
                        </main>
                    </div>
                </div>
            </body>
        </html>
    );
}
